---
name: "❓ Question"
description: 'Use this to ask a question. '
title: "[Question] - YourQuestion"
labels: ["question"]
projects: ["Future-Teaching-Institute/projects/1"]
assignees: []
body:
  - type: markdown
    attributes: 
      value : Ask your question or seek clarification on a specific topic.
  - type: textarea
    id: question
    attributes: 
      label: Your Question
      description: What can we or the community help with?
      placeholder: Are aliens cool or scary?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Pre-Submission Checklist
      description: Please ensure you've completed the below before posting your question
      options:
        - label: I have searched for existing answers or discussions related to my question.
          required: true
        - label: I have provided sufficient context and details to help others understand my question.
          required: true
        - label: I am open to receiving different perspectives or solutions.
          required: true
  - type: input
    id: contact
    attributes: 
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
