name: "\U0001F4EC Feature / Change Request"
description: A feature request in the form of a user story.
title: As a <User Type>, I would like <Something>, so that <Reason>
labels: Feature Request
projects: []
assignees: []
body: 
  - type: markdown
    attributes: 
      value: Provide a clear and detailed description of the feature or enhancement you are suggesting.
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior (If this is a change request)
      description: Describe the current behavior or functionality that the suggested feature should improve upon or add to.
    validations: 
      required: false
  - type: textarea
    id: use-cases
    attributes: 
      label: Use Case(s) / Scenario(s)
      description: Provide specific use case(s) or scenario(s) where this feature would be valuable or applicable.
    validations:
      required: true
  - type: textarea
    id: benefit-of-change
    attributes:
      label: Motivation for Change
      description: Explain the benefits or value that this feature / change would bring to the users or the project.
      placeholder: |
        - It would add hulk like strength to the internet
        - Batman might think it was cool
        - etc...
    validations: 
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Add any additional context, screenshots, or examples that can help in understanding and implementing the suggested feature.
    validations: 
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Pre-Submission Checklist
      description: Please ensure you've completed the below before posting your question
      options:
        - label: I have read the project's contributing guidelines and documentation.
          required: true
        - label: I have searched the existing issues to avoid duplicates.
          required: true
        - label: I am willing to contribute to this change and follow up on any feedback or questions.
          required: true
  - type: input
    id: contact
    attributes: 
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false